# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-16 18:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='upvoted_by',
        ),
        migrations.AddField(
            model_name='question',
            name='upvoted_by',
            field=models.ManyToManyField(related_name='questions_upvoted', to=settings.AUTH_USER_MODEL),
        ),
    ]
